# CUDA Hardware Configuration
hardware_name: cuda
display_name: CUDA Tests

ci_image: harbor.baai.ac.cn/flagos-dev/flagcx:55c5c6f-cuda-dev

runner_labels:
  - nv-8g-cicd-flagcx

container_volumes: []

container_options: >-
  --gpus all
  --privileged
  --ipc=host
  --ulimit memlock=-1
  --ulimit stack=67108864

set_env: .github/scripts/set_env/cuda.sh

unit_test_suites:
  - adaptor
  - core
  - device_api
  - p2p
  - rma
  - runner
  - service
  - symmem
