name: MetaX Unit Tests

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: metax-unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metax_unit_tests:
    name: MetaX unit tests
    uses: ./.github/workflows/unit_tests_platform_common.yml
    with:
      platform: metax
