name: "Unit Tests: symmem"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unittest-symmem:
    runs-on: [self-hosted, cx-build]
    container:
      image: localhost:5000/flagscale:cuda12.8.1-cudnn9.7.1-python3.12-torch2.7.0-time2507111538
      options: --gpus all --privileged --ipc=host --ulimit memlock=-1 --ulimit stack=67108864
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: true
          set-safe-directory: true

      - name: Build Google Test
        run: |
          cd /__w/FlagCX/FlagCX/third-party/googletest
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Build FlagCX
        run: |
          cd /__w/FlagCX/FlagCX
          export MPI_HOME=/usr/local/mpi
          make -j$(nproc) USE_NVIDIA=1

      - name: Build symmem tests
        run: |
          cd /__w/FlagCX/FlagCX/test/unittest/symmem
          export MPI_HOME=/usr/local/mpi
          make -j$(nproc)

      - name: Run symmem tests
        run: |
          cd /__w/FlagCX/FlagCX
          bash test/script/symmem_test.sh
